"""add_vot_dep_association

Revision ID: 21ea7cb6ae10
Revises: 78f0c4114e16
Create Date: 2025-10-10 14:28:20.730409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ea7cb6ae10'
down_revision: Union[str, Sequence[str], None] = '78f0c4114e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting_department_association',
    sa.Column('voting_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_department_association')
    # ### end Alembic commands ###
