"""voting_del_column_002

Revision ID: 685f4b6572d5
Revises: e24139d0ab26
Create Date: 2025-12-22 14:31:53.139068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '685f4b6572d5'
down_revision: Union[str, Sequence[str], None] = 'e24139d0ab26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votings', 'quorum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votings', sa.Column('quorum', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
