"""02_add_tables

Revision ID: 9b8182b1b69f
Revises: c227a9258545
Create Date: 2025-10-21 08:57:02.241087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8182b1b69f'
down_revision: Union[str, Sequence[str], None] = 'c227a9258545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SINGLE', 'MULTIPLE', name='questiontypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option', sa.String(length=255), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('votes', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('option_id', sa.Integer(), nullable=False))
    op.create_foreign_key("fk_votes_options", 'votes', 'options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("fk_votes_questions", 'votes', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_votes_options", 'votes', type_='foreignkey')
    op.drop_constraint("fk_votes_questions", 'votes', type_='foreignkey')
    op.drop_column('votes', 'option_id')
    op.drop_column('votes', 'question_id')
    op.drop_table('options')
    op.drop_table('questions')
    # ### end Alembic commands ###
