"""new_models

Revision ID: bfd73f489d7b
Revises: a7010edd427e
Create Date: 2025-10-03 14:15:23.940802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd73f489d7b'
down_revision: Union[str, Sequence[str], None] = 'a7010edd427e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('quorum', sa.Integer(), nullable=False),
    sa.Column('registration_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('registration_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('voting_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('voting_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archive_after', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_voting_registered_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('voting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], )
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id']),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('users_voting_registered_association')
    op.drop_table('votings')
    # ### end Alembic commands ###
